import { body } from "express-validator";

export const createListeningValidation = [
  body("name")
    .trim()
    .notEmpty()
    .withMessage("Tên bài kiểm tra không được để trống")
    .isLength({ min: 3, max: 200 })
    .withMessage("Tên bài kiểm tra phải từ 3-200 ký tự"),

  body("direction")
    .trim()
    .notEmpty()
    .withMessage("Hướng dẫn không được để trống")
    .isLength({ max: 5000 })
    .withMessage("Hướng dẫn không được vượt quá 5000 ký tự"),
];

export const createReadingValidation = [
  body("name")
    .trim()
    .notEmpty()
    .withMessage("Tên bài kiểm tra không được để trống")
    .isLength({ min: 3, max: 200 })
    .withMessage("Tên bài kiểm tra phải từ 3-200 ký tự"),

  body("direction")
    .trim()
    .notEmpty()
    .withMessage("Hướng dẫn không được để trống")
    .isLength({ max: 5000 })
    .withMessage("Hướng dẫn không được vượt quá 5000 ký tự"),
];

export const updateLRValidation = [
  body("name")
    .optional()
    .trim()
    .isLength({ min: 3, max: 200 })
    .withMessage("Tên bài kiểm tra phải từ 3-200 ký tự"),

  body("direction")
    .optional()
    .trim()
    .isLength({ max: 5000 })
    .withMessage("Hướng dẫn không được vượt quá 5000 ký tự"),
];

export const answerKeyValidation = [
  body("answers")
    .isArray({ min: 1 })
    .withMessage("Danh sách đáp án không được trống"),

  body("answers.*.index")
    .isInt({ min: 1, max: 200 })
    .withMessage("Chỉ số câu hỏi phải là số nguyên từ 1-200")
    .toInt(),

  body("answers.*.answer")
    .trim()
    .notEmpty()
    .withMessage("Đáp án không được để trống")
    .isIn(["A", "B", "C", "D"])
    .withMessage("Đáp án phải là A, B, C hoặc D"),
];

export const createPartOneQuestionValidation = [
  // audio and image are validated in the controller via req.files (multer)
  // question is not required for Part 1 (only image + audio needed)
  // index is auto-generated by the backend
];

export const createPartTwoQuestionValidation = [
  // audio is validated in the controller via req.files (multer)
  // question uses schema default: "Mark your answer on your answer sheet."
  // index is auto-generated by the backend
];

export const createPartFiveQuestionValidation = [
  // index is auto-generated by the backend

  body("question")
    .trim()
    .notEmpty()
    .withMessage("Câu hỏi không được để trống"),

  body("answerA")
    .trim()
    .notEmpty()
    .withMessage("Đáp án A không được để trống"),

  body("answerB")
    .trim()
    .notEmpty()
    .withMessage("Đáp án B không được để trống"),

  body("answerC")
    .trim()
    .notEmpty()
    .withMessage("Đáp án C không được để trống"),

  body("answerD")
    .trim()
    .notEmpty()
    .withMessage("Đáp án D không được để trống"),
];

export const createGroupValidation = [
  // index, fromQuestionIndex, toQuestionIndex are auto-generated by the backend

  body("questions")
    .customSanitizer((value) => {
      if (typeof value === "string") {
        try {
          return JSON.parse(value);
        } catch {
          return value;
        }
      }
      return value;
    })
    .isArray({ min: 1 })
    .withMessage("Danh sách câu hỏi không được trống"),

  body("questions.*.question")
    .trim()
    .notEmpty()
    .withMessage("Câu hỏi không được để trống"),

  body("questions.*.answerA")
    .trim()
    .notEmpty()
    .withMessage("Đáp án A không được để trống"),

  body("questions.*.answerB")
    .trim()
    .notEmpty()
    .withMessage("Đáp án B không được để trống"),

  body("questions.*.answerC")
    .trim()
    .notEmpty()
    .withMessage("Đáp án C không được để trống"),

  body("questions.*.answerD")
    .trim()
    .notEmpty()
    .withMessage("Đáp án D không được để trống"),
];

export const updatePartDirectionValidation = [
  body("direction")
    .trim()
    .notEmpty()
    .withMessage("Hướng dẫn không được để trống")
    .isLength({ max: 5000 })
    .withMessage("Hướng dẫn không được vượt quá 5000 ký tự"),
];
